"""
ADHD × AI 内容分类体系
10 大核心分类，每个分类包含选题模板和角度变量
"""

from dataclasses import dataclass, field


@dataclass
class Category:
    id: str
    name: str
    name_en: str
    description: str
    icon: str
    color: str
    keywords: list[str]
    angles: list[str]
    topics: list[dict] = field(default_factory=list)


CATEGORIES = [
    Category(
        id="ai-tools",
        name="AI工具实战",
        name_en="AI Tools in Practice",
        description="具体AI工具如何帮助ADHD人群提升效率、管理生活",
        icon="🛠️",
        color="#3B82F6",
        keywords=["AI工具", "效率工具", "ADHD辅助", "智能助手", "自动化"],
        angles=["工具评测", "使用技巧", "对比分析", "场景应用", "工作流搭建"],
        topics=[
            {"title": "ChatGPT 如何成为 ADHD 大脑的外接硬盘", "subtitle": "用对话式AI弥补工作记忆不足", "angle": "工具深度使用"},
            {"title": "10 个让 ADHD 患者效率翻倍的 AI 工具", "subtitle": "从任务管理到专注力追踪的完整工具包", "angle": "工具合集"},
            {"title": "Notion AI + ADHD：打造不会忘事的第二大脑", "subtitle": "用AI增强的笔记系统管理混乱思维", "angle": "具体工具"},
            {"title": "ADHD 友好的 AI 日程管理：让 AI 帮你规划每一天", "subtitle": "自动拆解任务、智能提醒、弹性调整", "angle": "场景应用"},
            {"title": "用 AI 语音助手征服 ADHD 的执行功能障碍", "subtitle": "语音指令如何绕过ADHD的启动困难", "angle": "交互方式"},
            {"title": "Copilot 时代：ADHD 程序员的超级外挂", "subtitle": "AI编程助手如何放大ADHD的创造力", "angle": "职业场景"},
            {"title": "AI 写作助手如何拯救 ADHD 的写作困难", "subtitle": "从大纲生成到全文润色的AI写作流程", "angle": "创作辅助"},
            {"title": "用 Midjourney 释放 ADHD 的视觉创造力", "subtitle": "AI绘图工具如何匹配ADHD的视觉思维", "angle": "创意工具"},
            {"title": "ADHD 必备：7 个 AI 自动化工作流", "subtitle": "用Zapier和Make打造自动运行的任务系统", "angle": "自动化"},
            {"title": "AI 阅读助手：帮助 ADHD 快速消化长文", "subtitle": "AI摘要、重点标注和交互式阅读", "angle": "学习工具"},
            {"title": "从混乱到有序：用 AI 整理 ADHD 的数字生活", "subtitle": "文件整理、邮件分类、照片管理的AI方案", "angle": "生活管理"},
            {"title": "ADHD 的 AI 备忘录系统：再也不怕忘事", "subtitle": "构建智能提醒和上下文感知的记忆辅助", "angle": "记忆辅助"},
            {"title": "用 AI 做 ADHD 的私人教练：运动、饮食、睡眠全管理", "subtitle": "AI如何帮助ADHD建立健康习惯", "angle": "健康管理"},
            {"title": "AI 翻译工具如何帮助 ADHD 学习外语", "subtitle": "利用AI的即时反馈匹配ADHD的学习节奏", "angle": "语言学习"},
            {"title": "ADHD + AI：打造个性化的信息过滤系统", "subtitle": "用AI屏蔽干扰、精选信息流", "angle": "信息管理"},
            {"title": "Claude vs ChatGPT：哪个更适合 ADHD 用户", "subtitle": "从对话风格到功能特性的全面对比", "angle": "工具对比"},
            {"title": "用 AI 思维导图工具驾驭 ADHD 的发散思维", "subtitle": "把跳跃的想法变成结构化的知识图谱", "angle": "思维工具"},
            {"title": "AI 财务助手：帮 ADHD 管好钱", "subtitle": "自动记账、预算提醒、消费分析", "angle": "财务管理"},
            {"title": "ADHD 的 AI 社交助手：不再错过重要的人际互动", "subtitle": "生日提醒、关系维护、沟通辅助", "angle": "社交管理"},
            {"title": "用 AI 搭建 ADHD 友好的知识管理系统", "subtitle": "碎片化学习的AI整合方案", "angle": "知识管理"},
            {"title": "AI 代码审查工具：ADHD 开发者的质量保障", "subtitle": "用AI弥补注意力疏忽导致的代码问题", "angle": "开发工具"},
            {"title": "ADHD 的 AI 邮件管理术：收件箱零焦虑", "subtitle": "自动分类、智能回复、优先级排序", "angle": "邮件管理"},
            {"title": "用 Perplexity AI 满足 ADHD 的好奇心", "subtitle": "AI搜索引擎如何让探索式学习更高效", "angle": "搜索工具"},
            {"title": "AI 项目管理工具：让 ADHD 团队协作不再混乱", "subtitle": "智能分配、进度追踪、自动同步", "angle": "团队协作"},
            {"title": "ADHD 的 AI 冥想引导：科技助力正念练习", "subtitle": "个性化冥想内容和进度追踪", "angle": "冥想工具"},
            {"title": "用 AI 视频工具释放 ADHD 的内容创造力", "subtitle": "从脚本到剪辑的一站式AI视频制作", "angle": "视频创作"},
            {"title": "AI 习惯追踪器：帮 ADHD 建立可持续的好习惯", "subtitle": "智能提醒、适应性调整、正向反馈", "angle": "习惯养成"},
            {"title": "ADHD 的 AI 旅行助手：告别出行混乱", "subtitle": "智能行程规划、文档管理、实时提醒", "angle": "旅行管理"},
            {"title": "用 AI 播客工具开启 ADHD 的声音创业", "subtitle": "从录制到发布的全自动化播客流程", "angle": "播客创作"},
            {"title": "AI 家居管理：帮 ADHD 打造有序的生活空间", "subtitle": "智能清洁提醒、物品追踪、空间规划", "angle": "家居管理"},
            {"title": "ADHD 的 AI 数据分析伙伴", "subtitle": "让AI处理ADHD最不擅长的数据整理工作", "angle": "数据分析"},
            {"title": "用 AI 做 ADHD 的会议助手", "subtitle": "自动记录、提取要点、生成待办事项", "angle": "会议管理"},
            {"title": "AI 演示文稿工具：帮 ADHD 做出惊艳的 PPT", "subtitle": "从内容组织到视觉设计的AI自动化", "angle": "演示工具"},
            {"title": "ADHD 的 AI 客服系统搭建指南", "subtitle": "用AI自动化处理重复性客户沟通", "angle": "客服自动化"},
            {"title": "用 AI 音乐工具提升 ADHD 的专注力", "subtitle": "AI生成的专注音乐和白噪音", "angle": "音乐工具"},
            {"title": "AI 法律助手：帮 ADHD 创业者处理合同文书", "subtitle": "合同审核、条款解读、风险提示", "angle": "法律工具"},
            {"title": "ADHD 的 AI 穿搭助手：告别每天穿什么的决策疲劳", "subtitle": "AI搭配推荐减少日常决策负担", "angle": "穿搭管理"},
            {"title": "用 AI 表格工具征服 ADHD 的数据恐惧", "subtitle": "自然语言操作Excel和数据库", "angle": "表格工具"},
            {"title": "AI 设计工具让 ADHD 的创意快速落地", "subtitle": "从想法到设计稿的AI加速流程", "angle": "设计工具"},
            {"title": "ADHD 的 AI 工具使用指南：避坑与最佳实践", "subtitle": "如何不被工具淹没，建立可持续的AI使用习惯", "angle": "使用方法论"},
        ],
    ),
    Category(
        id="focus",
        name="专注力管理",
        name_en="Focus Management",
        description="AI辅助的专注力提升策略和方法",
        icon="🎯",
        color="#8B5CF6",
        keywords=["专注力", "注意力", "深度工作", "心流", "分心管理"],
        angles=["方法论", "科学原理", "实践技巧", "工具辅助", "环境设计"],
        topics=[
            {"title": "AI 如何帮 ADHD 进入心流状态", "subtitle": "用技术制造专注力的触发条件", "angle": "心流理论"},
            {"title": "ADHD 的 AI 番茄钟：智能适应你的注意力节奏", "subtitle": "AI动态调整工作和休息时间", "angle": "时间技术"},
            {"title": "用 AI 分析你的注意力模式", "subtitle": "发现你一天中最专注的时段", "angle": "数据分析"},
            {"title": "AI 驱动的分心拦截系统", "subtitle": "智能识别和阻断分心行为", "angle": "防分心"},
            {"title": "ADHD 的超级专注力：如何用 AI 引导而非压制", "subtitle": "利用ADHD的超专注特质而非对抗它", "angle": "优势视角"},
            {"title": "环境噪音 + AI：找到你的最佳专注声景", "subtitle": "AI生成个性化的环境音频", "angle": "环境设计"},
            {"title": "AI 生物反馈：实时监测 ADHD 的注意力状态", "subtitle": "可穿戴设备+AI的注意力追踪", "angle": "生物技术"},
            {"title": "深度工作 2.0：ADHD 版的 AI 辅助深度工作法", "subtitle": "Cal Newport方法论的ADHD适配", "angle": "方法论"},
            {"title": "用 AI 管理 ADHD 的浏览器标签页成瘾", "subtitle": "智能标签管理和阅读队列", "angle": "数字习惯"},
            {"title": "ADHD 的 AI 冥想教练：从1分钟开始", "subtitle": "用AI设计ADHD友好的渐进式冥想", "angle": "冥想练习"},
            {"title": "AI 帮你设计 ADHD 友好的工作环境", "subtitle": "从照明到桌面布局的智能建议", "angle": "空间设计"},
            {"title": "从分心到专注：AI 训练 ADHD 注意力的5个阶段", "subtitle": "基于神经可塑性的AI训练方案", "angle": "训练方法"},
            {"title": "ADHD 的注意力银行：用 AI 管理你的认知资源", "subtitle": "量化注意力消耗和恢复", "angle": "资源管理"},
            {"title": "AI 如何帮 ADHD 抵抗即时满足的诱惑", "subtitle": "智能延迟奖励和习惯重塑", "angle": "行为设计"},
            {"title": "ADHD 多任务处理的 AI 解决方案", "subtitle": "AI帮你在任务间智能切换而非混乱切换", "angle": "多任务管理"},
            {"title": "用 AI 追踪和提升 ADHD 的专注力指标", "subtitle": "建立个人专注力数据看板", "angle": "数据量化"},
            {"title": "ADHD 的 AI 游戏化专注系统", "subtitle": "把专注力训练变成有趣的游戏", "angle": "游戏化"},
            {"title": "晨间仪式 + AI：帮 ADHD 建立每天的专注启动程序", "subtitle": "AI设计个性化的晨间唤醒流程", "angle": "日常仪式"},
            {"title": "AI 如何帮 ADHD 管理信息过载", "subtitle": "智能信息筛选和消化策略", "angle": "信息管理"},
            {"title": "ADHD 的 AI 专注力恢复方案", "subtitle": "当注意力耗尽时的AI辅助恢复策略", "angle": "恢复方法"},
            {"title": "用 AI 识别 ADHD 的分心触发器", "subtitle": "数据驱动的分心模式分析", "angle": "触发器分析"},
            {"title": "ADHD 的 AI 白噪音生成器：科学设计的专注音频", "subtitle": "基于脑科学的AI音频环境", "angle": "音频工具"},
            {"title": "AI 微习惯教练：帮 ADHD 用2分钟开始专注", "subtitle": "用AI驱动的微小起步克服启动困难", "angle": "微习惯"},
            {"title": "ADHD 的注意力训练 App 评测：AI 加持的专注力提升", "subtitle": "10款AI注意力训练应用深度评测", "angle": "应用评测"},
            {"title": "用 AI 创建 ADHD 的专注力清单", "subtitle": "智能检查清单帮你保持在轨道上", "angle": "清单工具"},
            {"title": "ADHD 的 AI 呼吸教练：用呼吸技术提升专注力", "subtitle": "AI引导的呼吸练习实时反馈", "angle": "呼吸训练"},
            {"title": "AI 帮 ADHD 设计完美的「专注洞穴」", "subtitle": "数据驱动的个人专注空间设计", "angle": "空间优化"},
            {"title": "ADHD 的 AI 屏幕时间管理策略", "subtitle": "智能限制和引导屏幕使用", "angle": "屏幕管理"},
            {"title": "用 AI 实现 ADHD 的「身体倍增」专注法", "subtitle": "让身体运动帮助大脑专注的AI方案", "angle": "运动专注"},
            {"title": "ADHD 的 AI 任务启动助手：克服「知道该做却做不了」", "subtitle": "AI分解启动障碍的具体策略", "angle": "启动辅助"},
            {"title": "AI 专注力教练 vs 人类教练：ADHD 该怎么选", "subtitle": "两种教练方式的优劣势分析", "angle": "方案对比"},
            {"title": "用 AI 日记分析 ADHD 的专注力变化趋势", "subtitle": "长期数据追踪优化专注力策略", "angle": "趋势分析"},
            {"title": "ADHD 的 AI 阅读专注辅助", "subtitle": "AI帮你从「读不下去」到「深度阅读」", "angle": "阅读专注"},
            {"title": "AI 帮 ADHD 管理「兴趣驱动」的专注力", "subtitle": "利用而非对抗ADHD的兴趣依赖特质", "angle": "兴趣管理"},
            {"title": "ADHD 学生的 AI 课堂专注力辅助方案", "subtitle": "让AI成为课堂上的隐形专注力教练", "angle": "学习场景"},
            {"title": "用 AI 打造 ADHD 的专注力奖励系统", "subtitle": "即时反馈和正向强化的AI设计", "angle": "奖励系统"},
            {"title": "ADHD 的 AI 驾驶专注辅助", "subtitle": "行车安全的AI注意力监测方案", "angle": "驾驶安全"},
            {"title": "AI 如何帮 ADHD 管理考试专注力", "subtitle": "考试场景的专注力策略和AI辅助", "angle": "考试场景"},
            {"title": "ADHD 的 AI 专注力社区：一起专注的力量", "subtitle": "AI匹配的虚拟专注力伙伴", "angle": "社区力量"},
            {"title": "2025 年 ADHD 专注力管理的 AI 趋势", "subtitle": "最新的AI专注力技术和发展方向", "angle": "趋势展望"},
        ],
    ),
    Category(
        id="time-mgmt",
        name="时间管理",
        name_en="Time Management",
        description="AI驱动的ADHD时间管理和任务规划",
        icon="⏰",
        color="#F59E0B",
        keywords=["时间管理", "任务规划", "日程安排", "拖延", "优先级"],
        angles=["方法论", "工具应用", "习惯建设", "拖延对策", "规划技巧"],
        topics=[
            {"title": "ADHD 的时间盲：AI 如何帮你「看见」时间", "subtitle": "用AI可视化和量化时间感知", "angle": "时间感知"},
            {"title": "AI 帮 ADHD 克服拖延症的 7 个策略", "subtitle": "基于行为科学的AI抗拖延方案", "angle": "拖延对策"},
            {"title": "ADHD 的 AI 智能日程：告别过度承诺", "subtitle": "AI帮你估算真实所需时间", "angle": "日程规划"},
            {"title": "用 AI 帮 ADHD 拆解大任务为小步骤", "subtitle": "AI任务分解让每一步都可执行", "angle": "任务拆解"},
            {"title": "ADHD 的截止日期焦虑：AI 的缓冲区策略", "subtitle": "AI自动建立安全缓冲和进度追踪", "angle": "截止日期"},
            {"title": "AI 时间记录：帮 ADHD 找到时间都去哪了", "subtitle": "自动时间追踪和分析报告", "angle": "时间追踪"},
            {"title": "ADHD 的 AI 优先级矩阵", "subtitle": "AI帮你判断什么该先做什么该后做", "angle": "优先级"},
            {"title": "用 AI 设计 ADHD 的理想一天", "subtitle": "基于个人数据的AI日程优化", "angle": "日程设计"},
            {"title": "ADHD 的 AI 周计划系统", "subtitle": "灵活但有结构的周规划方法", "angle": "周计划"},
            {"title": "AI 如何帮 ADHD 管理多个项目", "subtitle": "AI项目看板和进度自动跟踪", "angle": "多项目管理"},
            {"title": "ADHD 的时间膨胀问题：AI 的时间锚定方案", "subtitle": "用AI校准ADHD扭曲的时间感知", "angle": "时间校准"},
            {"title": "用 AI 建立 ADHD 的晨间和晚间例行程序", "subtitle": "AI设计的渐进式日常例程", "angle": "日常例程"},
            {"title": "ADHD 的 AI 等待管理：把等待变成生产力", "subtitle": "AI帮你利用碎片时间", "angle": "碎片时间"},
            {"title": "AI 帮 ADHD 说「不」：智能时间保护策略", "subtitle": "AI辅助的边界设定和时间保护", "angle": "时间边界"},
            {"title": "ADHD 的 AI 会议时间管理", "subtitle": "控制会议时间、提取行动项", "angle": "会议管理"},
            {"title": "用 AI 帮 ADHD 建立时间感知训练", "subtitle": "通过AI训练提升时间估算能力", "angle": "能力训练"},
            {"title": "ADHD 的 AI 紧急-重要矩阵", "subtitle": "AI自动分类任务紧急程度和重要性", "angle": "任务分类"},
            {"title": "AI 帮 ADHD 管理「过渡时间」", "subtitle": "任务切换间隙的AI辅助策略", "angle": "过渡管理"},
            {"title": "ADHD 的 AI 季度回顾系统", "subtitle": "用AI做定期的时间使用复盘", "angle": "回顾复盘"},
            {"title": "用 AI 打败 ADHD 的「分析瘫痪」", "subtitle": "AI帮你快速决策不再纠结", "angle": "决策辅助"},
            {"title": "ADHD 的 AI 家务时间管理", "subtitle": "让AI帮你把家务变成可管理的系统", "angle": "家务管理"},
            {"title": "AI 帮 ADHD 管理考试和学习时间", "subtitle": "考前复习的AI智能时间分配", "angle": "学习时间"},
            {"title": "ADHD 的 AI 休息提醒：工作和休息的黄金比例", "subtitle": "AI动态调整工作休息节奏", "angle": "休息管理"},
            {"title": "用 AI 帮 ADHD 准时到达每个约会", "subtitle": "出发提醒、路线规划、准备时间提示", "angle": "出行准时"},
            {"title": "ADHD 的 AI 年度目标追踪系统", "subtitle": "把大目标拆解为AI可追踪的里程碑", "angle": "目标管理"},
            {"title": "AI 帮 ADHD 管理「内疚时间」", "subtitle": "用AI消除因时间浪费产生的内疚感", "angle": "情绪管理"},
            {"title": "ADHD 的 AI 社交时间管理", "subtitle": "AI帮你平衡社交和独处时间", "angle": "社交时间"},
            {"title": "用 AI 管理 ADHD 的假期和休假", "subtitle": "避免假期计划过满或完全虚度", "angle": "假期规划"},
            {"title": "ADHD 的 AI 批量处理策略", "subtitle": "用AI打包相似任务提升处理效率", "angle": "批量处理"},
            {"title": "AI 帮 ADHD 管理异步工作时间", "subtitle": "远程工作中的AI时间管理方案", "angle": "远程工作"},
            {"title": "ADHD 的 AI 时间预算系统", "subtitle": "像管理金钱一样用AI管理时间", "angle": "时间预算"},
            {"title": "用 AI 帮 ADHD 建立「时间块」工作法", "subtitle": "AI优化的时间块分配和执行", "angle": "时间块"},
            {"title": "ADHD 的 AI 通勤时间优化", "subtitle": "通勤路上的AI学习和效率方案", "angle": "通勤利用"},
            {"title": "AI 帮 ADHD 管理「能量时间」vs「低谷时间」", "subtitle": "根据精力曲线智能分配任务", "angle": "能量管理"},
            {"title": "ADHD 的 AI 项目截止日倒推系统", "subtitle": "从截止日期自动倒推每日任务量", "angle": "倒推规划"},
            {"title": "用 AI 帮 ADHD 进行每日5分钟计划", "subtitle": "最小化的每日规划AI辅助", "angle": "简易规划"},
            {"title": "ADHD 的 AI 时间日志分析", "subtitle": "用AI发现你的时间使用模式和浪费点", "angle": "日志分析"},
            {"title": "AI 帮 ADHD 管理家庭和工作的时间冲突", "subtitle": "智能平衡工作和家庭时间", "angle": "平衡冲突"},
            {"title": "ADHD 的 AI 睡眠时间管理", "subtitle": "AI帮助建立规律的睡眠作息", "angle": "睡眠管理"},
            {"title": "用 AI 打造 ADHD 的时间管理仪表盘", "subtitle": "一目了然的个人时间管理数据可视化", "angle": "数据看板"},
        ],
    ),
    Category(
        id="emotion",
        name="情绪调节",
        name_en="Emotional Regulation",
        description="AI辅助的ADHD情绪管理和心理健康",
        icon="💚",
        color="#10B981",
        keywords=["情绪管理", "焦虑", "自我接纳", "心理健康", "压力管理"],
        angles=["情绪识别", "调节策略", "自我关怀", "人际关系", "心理治疗"],
        topics=[
            {"title": "ADHD 的情绪过山车：AI 如何帮你平稳着陆", "subtitle": "用AI追踪和预测情绪波动", "angle": "情绪追踪"},
            {"title": "AI 情绪日记：帮 ADHD 理解自己的情绪模式", "subtitle": "自然语言情绪分析和趋势发现", "angle": "情绪记录"},
            {"title": "ADHD 的拒绝敏感性：AI 的认知重构辅助", "subtitle": "用AI挑战和重塑负面思维模式", "angle": "认知重构"},
            {"title": "用 AI 管理 ADHD 的焦虑感", "subtitle": "AI驱动的焦虑缓解策略和练习", "angle": "焦虑管理"},
            {"title": "ADHD 的 AI 愤怒管理方案", "subtitle": "AI识别愤怒触发器和冷静策略", "angle": "愤怒管理"},
            {"title": "AI 如何帮 ADHD 建立自我同情", "subtitle": "用AI练习自我关怀和接纳", "angle": "自我关怀"},
            {"title": "ADHD 的 AI 压力监测系统", "subtitle": "实时压力水平追踪和干预建议", "angle": "压力管理"},
            {"title": "用 AI 帮 ADHD 处理完美主义", "subtitle": "AI辅助的「足够好」标准设定", "angle": "完美主义"},
            {"title": "ADHD 的 AI 正念练习指南", "subtitle": "专为ADHD设计的AI正念方案", "angle": "正念练习"},
            {"title": "AI 帮 ADHD 管理工作倦怠", "subtitle": "早期预警和恢复策略", "angle": "倦怠管理"},
            {"title": "ADHD 的 AI 自尊心修复计划", "subtitle": "用AI建立正向的自我认知", "angle": "自尊建设"},
            {"title": "用 AI 帮 ADHD 处理挫折感", "subtitle": "任务失败后的AI情绪恢复辅助", "angle": "挫折应对"},
            {"title": "ADHD 的 AI 情绪急救包", "subtitle": "情绪崩溃时的AI即时干预工具", "angle": "情绪急救"},
            {"title": "AI 如何帮 ADHD 改善亲密关系中的情绪管理", "subtitle": "AI辅助的情侣/夫妻沟通策略", "angle": "亲密关系"},
            {"title": "ADHD 的 AI 感恩练习", "subtitle": "用AI引导每日感恩习惯", "angle": "感恩练习"},
            {"title": "用 AI 帮 ADHD 处理社交焦虑", "subtitle": "社交场景的AI情绪准备和恢复", "angle": "社交焦虑"},
            {"title": "ADHD 的 AI 情绪教育课", "subtitle": "用AI学习识别和命名自己的情绪", "angle": "情绪教育"},
            {"title": "AI 帮 ADHD 管理节假日情绪", "subtitle": "节日期间的特殊情绪管理策略", "angle": "节日情绪"},
            {"title": "ADHD 的 AI 职场情绪管理", "subtitle": "AI帮你在工作中保持情绪稳定", "angle": "职场情绪"},
            {"title": "用 AI 帮 ADHD 建立情绪恢复力", "subtitle": "长期的情绪韧性训练方案", "angle": "情绪韧性"},
            {"title": "ADHD 的 AI 睡前情绪调节", "subtitle": "AI引导的睡前放松和情绪整理", "angle": "睡前调节"},
            {"title": "AI 帮 ADHD 管理「决策后悔」情绪", "subtitle": "用AI减少决策后的自我批评", "angle": "决策后悔"},
            {"title": "ADHD 的 AI 运动情绪调节方案", "subtitle": "AI推荐的运动处方和情绪提升", "angle": "运动调节"},
            {"title": "用 AI 帮 ADHD 管理药物情绪波动", "subtitle": "药物副作用的情绪追踪和管理", "angle": "药物管理"},
            {"title": "ADHD 的 AI 创意情绪出口", "subtitle": "用AI艺术工具释放和表达情绪", "angle": "创意表达"},
            {"title": "AI 帮 ADHD 识别情绪性进食", "subtitle": "情绪化饮食的AI干预方案", "angle": "情绪饮食"},
            {"title": "ADHD 的 AI 情绪天气预报", "subtitle": "AI预测你的情绪走势", "angle": "情绪预测"},
            {"title": "用 AI 帮 ADHD 建立安全的情绪表达", "subtitle": "AI辅助的健康情绪表达训练", "angle": "情绪表达"},
            {"title": "ADHD 的 AI 共情训练", "subtitle": "用AI提升理解他人情绪的能力", "angle": "共情训练"},
            {"title": "AI 帮 ADHD 管理季节性情绪波动", "subtitle": "季节变化对ADHD情绪的影响和AI应对", "angle": "季节影响"},
            {"title": "ADHD 的 AI 自我对话改善", "subtitle": "用AI识别和转变消极的内心对话", "angle": "自我对话"},
            {"title": "用 AI 建立 ADHD 的情绪支持网络", "subtitle": "AI匹配的同伴支持和情绪互助", "angle": "支持网络"},
            {"title": "ADHD 的 AI 情绪边界设定", "subtitle": "AI帮你建立和维护健康的情绪边界", "angle": "边界设定"},
            {"title": "AI 帮 ADHD 管理多巴胺寻求行为", "subtitle": "AI识别和引导健康的多巴胺获取方式", "angle": "多巴胺管理"},
            {"title": "ADHD 的 AI 情绪复盘系统", "subtitle": "用AI定期分析情绪事件和成长", "angle": "情绪复盘"},
            {"title": "用 AI 帮 ADHD 准备高压情境", "subtitle": "面试、演讲等高压场景的AI情绪准备", "angle": "高压准备"},
            {"title": "ADHD 的 AI 情绪传染管理", "subtitle": "AI帮你识别和管理他人情绪的影响", "angle": "情绪传染"},
            {"title": "AI 帮 ADHD 建立「情绪安全岛」", "subtitle": "AI打造的个人情绪避风港", "angle": "安全空间"},
            {"title": "ADHD 的 AI CBT 认知行为训练", "subtitle": "AI辅助的认知行为疗法自助训练", "angle": "CBT训练"},
            {"title": "用 AI 记录和庆祝 ADHD 的每一个小胜利", "subtitle": "AI帮你看到被忽视的进步和成就", "angle": "成就记录"},
        ],
    ),
    Category(
        id="learning",
        name="学习方法",
        name_en="Learning Methods",
        description="ADHD友好的AI辅助学习策略",
        icon="📚",
        color="#EC4899",
        keywords=["学习方法", "记忆", "考试", "终身学习", "技能提升"],
        angles=["学习策略", "记忆技巧", "考试准备", "在线学习", "技能习得"],
        topics=[
            {"title": "ADHD 的 AI 学习革命：为什么传统学习方法不适合你", "subtitle": "ADHD大脑的学习特点和AI适配方案", "angle": "学习理论"},
            {"title": "AI 闪卡系统：ADHD 的超级记忆术", "subtitle": "AI优化的间隔重复和记忆强化", "angle": "记忆技术"},
            {"title": "ADHD 的 AI 个性化学习路径", "subtitle": "AI根据你的学习风格定制学习计划", "angle": "个性化"},
            {"title": "用 AI 帮 ADHD 学生做笔记：从混乱到系统", "subtitle": "AI辅助的笔记整理和知识结构化", "angle": "笔记方法"},
            {"title": "ADHD 的 AI 考试准备神器", "subtitle": "AI生成的复习计划和模拟测试", "angle": "考试准备"},
            {"title": "AI 如何帮 ADHD 实现「20分钟学习法」", "subtitle": "匹配ADHD注意力窗口的AI微学习", "angle": "微学习"},
            {"title": "ADHD 的 AI 语言学习加速器", "subtitle": "利用ADHD的模式识别优势学外语", "angle": "语言学习"},
            {"title": "用 AI 帮 ADHD 建立学习兴趣循环", "subtitle": "AI如何维持ADHD对学习的兴趣", "angle": "兴趣维持"},
            {"title": "ADHD 的 AI 编程学习指南", "subtitle": "为什么ADHD+AI是学编程的最佳组合", "angle": "编程学习"},
            {"title": "AI 导师：ADHD 学生的24/7学习伙伴", "subtitle": "随时提问、即时反馈的AI学习辅助", "angle": "AI导师"},
            {"title": "ADHD 的 AI 视觉学习方案", "subtitle": "利用ADHD的视觉优势进行AI辅助学习", "angle": "视觉学习"},
            {"title": "用 AI 帮 ADHD 克服「学习启动困难」", "subtitle": "AI消除学习开始前的摩擦力", "angle": "启动困难"},
            {"title": "ADHD 的 AI 概念图谱学习法", "subtitle": "AI帮你把知识连接成网络而非线性列表", "angle": "概念映射"},
            {"title": "AI 帮 ADHD 创建「学习播放列表」", "subtitle": "像听歌一样学习的AI学习内容编排", "angle": "学习编排"},
            {"title": "ADHD 的 AI 实践学习法", "subtitle": "AI驱动的项目制学习和动手实践", "angle": "实践学习"},
            {"title": "用 AI 帮 ADHD 管理在线课程学习", "subtitle": "防止买课不看的AI学习推进系统", "angle": "在线课程"},
            {"title": "ADHD 的 AI 费曼学习法", "subtitle": "用AI当你的「学习听众」来深化理解", "angle": "费曼学习"},
            {"title": "AI 帮 ADHD 建立知识回顾系统", "subtitle": "防止学了就忘的AI复习提醒", "angle": "知识复习"},
            {"title": "ADHD 的 AI 数学学习辅助", "subtitle": "AI如何帮ADHD克服数学焦虑", "angle": "数学学习"},
            {"title": "用 AI 帮 ADHD 做学术研究", "subtitle": "文献检索、论文阅读的AI加速", "angle": "学术研究"},
            {"title": "ADHD 的 AI 音频学习方案", "subtitle": "利用AI音频工具实现通勤学习", "angle": "音频学习"},
            {"title": "AI 帮 ADHD 学生准备论文写作", "subtitle": "从选题到答辩的AI全程辅助", "angle": "论文写作"},
            {"title": "ADHD 的 AI 职业技能学习路线图", "subtitle": "AI规划的技能提升路径", "angle": "技能规划"},
            {"title": "用 AI 帮 ADHD 进行「快速原型学习」", "subtitle": "通过AI快速实现想法来学习新技能", "angle": "快速原型"},
            {"title": "ADHD 的 AI 团队学习组织", "subtitle": "AI匹配学习伙伴和组织学习小组", "angle": "协作学习"},
            {"title": "AI 帮 ADHD 把兴趣变成专业知识", "subtitle": "利用ADHD的深度兴趣进行系统学习", "angle": "兴趣深化"},
            {"title": "ADHD 的 AI 教学相长法", "subtitle": "用AI帮你通过教别人来学习", "angle": "教学学习"},
            {"title": "用 AI 帮 ADHD 管理学习焦虑", "subtitle": "AI缓解「学不完」焦虑的策略", "angle": "学习焦虑"},
            {"title": "ADHD 的 AI 沉浸式学习环境", "subtitle": "AI打造的虚拟学习空间", "angle": "沉浸学习"},
            {"title": "AI 帮 ADHD 进行跨学科学习", "subtitle": "利用ADHD的联想能力进行跨领域整合", "angle": "跨学科"},
            {"title": "ADHD 的 AI 错题本系统", "subtitle": "AI自动收集和分析错误模式", "angle": "错题分析"},
            {"title": "用 AI 帮 ADHD 制定「不完美学习计划」", "subtitle": "用80/20法则的AI学习优化", "angle": "效率学习"},
            {"title": "ADHD 的 AI 认证考试准备方案", "subtitle": "AI辅助的专业认证考试复习", "angle": "认证考试"},
            {"title": "AI 帮 ADHD 学习如何学习", "subtitle": "用AI元学习提升学习能力本身", "angle": "元学习"},
            {"title": "ADHD 的 AI 阅读理解增强", "subtitle": "AI帮你从「读过」到「读懂」", "angle": "阅读理解"},
            {"title": "用 AI 帮 ADHD 做学习进度可视化", "subtitle": "看得见的进步激发ADHD的学习动力", "angle": "进度可视化"},
            {"title": "ADHD 的 AI 学习游戏化方案", "subtitle": "把学习变成RPG的AI系统", "angle": "游戏化"},
            {"title": "AI 帮 ADHD 建立终身学习系统", "subtitle": "AI驱动的持续学习和成长框架", "angle": "终身学习"},
            {"title": "ADHD 的 AI 艺术和音乐学习", "subtitle": "创意领域的AI辅助学习方案", "angle": "艺术学习"},
            {"title": "用 AI 帮 ADHD 做学习成果展示", "subtitle": "把学习成果转化为作品集的AI辅助", "angle": "成果展示"},
        ],
    ),
    Category(
        id="career",
        name="职场发展",
        name_en="Career Development",
        description="ADHD职场人在AI时代的竞争力和发展",
        icon="💼",
        color="#6366F1",
        keywords=["职场", "求职", "晋升", "领导力", "远程工作"],
        angles=["职场优势", "求职策略", "团队协作", "远程工作", "职业规划"],
        topics=[
            {"title": "ADHD 在 AI 时代的 5 大职场超能力", "subtitle": "为什么ADHD特质在AI时代更有价值", "angle": "优势视角"},
            {"title": "AI 帮 ADHD 写出完美的简历和求职信", "subtitle": "AI辅助的个性化求职材料", "angle": "求职准备"},
            {"title": "ADHD 程序员在 AI 时代的独特优势", "subtitle": "创造力和快速迭代能力的价值", "angle": "技术职业"},
            {"title": "用 AI 帮 ADHD 准备面试：从焦虑到自信", "subtitle": "AI模拟面试和表现优化", "angle": "面试准备"},
            {"title": "ADHD 的 AI 职场沟通助手", "subtitle": "AI帮你写邮件、做汇报、管理上级期望", "angle": "沟通技巧"},
            {"title": "AI 时代的 ADHD 领导力", "subtitle": "ADHD管理者如何用AI放大领导优势", "angle": "领导力"},
            {"title": "ADHD 的远程工作 AI 生存指南", "subtitle": "远程环境下的AI自我管理方案", "angle": "远程工作"},
            {"title": "AI 帮 ADHD 管理工作中的人际关系", "subtitle": "职场社交的AI辅助策略", "angle": "职场人际"},
            {"title": "ADHD 的 AI 职业规划师", "subtitle": "AI帮你找到最适合ADHD的职业方向", "angle": "职业规划"},
            {"title": "用 AI 帮 ADHD 管理绩效评估", "subtitle": "AI记录成就、准备评估材料", "angle": "绩效管理"},
            {"title": "ADHD 的 AI 副业启动指南", "subtitle": "用AI低成本启动第二收入来源", "angle": "副业"},
            {"title": "AI 帮 ADHD 处理职场冲突", "subtitle": "AI辅助的冲突识别和解决策略", "angle": "冲突管理"},
            {"title": "ADHD 在 AI 行业的就业机会", "subtitle": "AI行业中最适合ADHD的岗位", "angle": "行业机会"},
            {"title": "用 AI 帮 ADHD 做职场网络建设", "subtitle": "AI辅助的LinkedIn经营和人脉管理", "angle": "人脉建设"},
            {"title": "ADHD 的 AI 工作报告生成器", "subtitle": "自动生成周报、月报、项目总结", "angle": "工作汇报"},
            {"title": "AI 帮 ADHD 管理工作中的完美主义", "subtitle": "AI设定的「完成比完美更重要」系统", "angle": "完美主义"},
            {"title": "ADHD 的 AI 薪资谈判准备", "subtitle": "AI辅助的市场调研和谈判策略", "angle": "薪资谈判"},
            {"title": "用 AI 帮 ADHD 建立个人品牌", "subtitle": "AI内容创作和社交媒体管理", "angle": "个人品牌"},
            {"title": "ADHD 的 AI 团队管理工具包", "subtitle": "AI辅助的团队协调和项目管理", "angle": "团队管理"},
            {"title": "AI 帮 ADHD 管理工作中的注意力分配", "subtitle": "AI优化的工作专注力策略", "angle": "工作专注"},
            {"title": "ADHD 设计师在 AI 时代的竞争力", "subtitle": "创意思维+AI工具的设计师优势", "angle": "设计职业"},
            {"title": "用 AI 帮 ADHD 做职场转型", "subtitle": "AI辅助的职业转型规划和技能补充", "angle": "职业转型"},
            {"title": "ADHD 的 AI 自由职业生存指南", "subtitle": "用AI管理自由职业的不确定性", "angle": "自由职业"},
            {"title": "AI 帮 ADHD 在开放式办公室生存", "subtitle": "AI辅助的噪音管理和专注策略", "angle": "办公环境"},
            {"title": "ADHD 的 AI 客户关系管理", "subtitle": "AI帮你跟进客户和维护关系", "angle": "客户管理"},
            {"title": "用 AI 帮 ADHD 做会议准备和跟进", "subtitle": "AI的会议前后自动化工作流", "angle": "会议效率"},
            {"title": "ADHD 的 AI 职场情商提升", "subtitle": "AI辅助的职场情绪智力训练", "angle": "情商提升"},
            {"title": "AI 帮 ADHD 应对职场变化和不确定性", "subtitle": "AI辅助的适应力和韧性建设", "angle": "适应变化"},
            {"title": "ADHD 内容创作者的 AI 工作流", "subtitle": "AI驱动的内容生产系统", "angle": "内容创作"},
            {"title": "用 AI 帮 ADHD 做时间账单管理", "subtitle": "自由职业和咨询的AI计时计费", "angle": "计时计费"},
            {"title": "ADHD 教师在 AI 时代的教学优势", "subtitle": "ADHD教师如何用AI创新教学", "angle": "教育职业"},
            {"title": "AI 帮 ADHD 管理多角色工作", "subtitle": "身兼多职的AI任务切换和角色管理", "angle": "多角色"},
            {"title": "ADHD 的 AI 职场心理安全感建设", "subtitle": "AI帮你建立工作中的自信和安全感", "angle": "心理安全"},
            {"title": "用 AI 帮 ADHD 做职场演讲准备", "subtitle": "AI辅助的演讲稿撰写和练习", "angle": "演讲准备"},
            {"title": "ADHD 销售人员的 AI 超级武器", "subtitle": "AI如何放大ADHD销售人员的天然优势", "angle": "销售职业"},
            {"title": "AI 帮 ADHD 管理工作中的deadline", "subtitle": "AI的截止日期追踪和紧急任务管理", "angle": "截止日期"},
            {"title": "ADHD 的 AI 持续学习和职业成长", "subtitle": "AI规划的职业技能发展路径", "angle": "持续学习"},
            {"title": "用 AI 帮 ADHD 做工作交接", "subtitle": "AI辅助的知识转移和工作交接文档", "angle": "工作交接"},
            {"title": "ADHD 的 AI 职场导师匹配", "subtitle": "AI帮你找到最适合的职业导师", "angle": "导师关系"},
            {"title": "AI 时代 ADHD 最有前景的 10 个职业方向", "subtitle": "未来5年ADHD+AI的职业趋势分析", "angle": "趋势分析"},
        ],
    ),
    Category(
        id="entrepreneurship",
        name="创业创新",
        name_en="Entrepreneurship & Innovation",
        description="ADHD创业者如何利用AI获得竞争优势",
        icon="🚀",
        color="#F97316",
        keywords=["创业", "创新", "商业", "产品", "市场营销"],
        angles=["创业优势", "商业模式", "产品开发", "营销策略", "融资管理"],
        topics=[
            {"title": "ADHD 创业者的 AI 超级力量", "subtitle": "为什么最成功的创业者很多有ADHD", "angle": "创业优势"},
            {"title": "用 AI 帮 ADHD 创业者验证商业想法", "subtitle": "AI快速市场验证和MVP设计", "angle": "想法验证"},
            {"title": "ADHD 的 AI 一人公司运营指南", "subtitle": "AI自动化让一个人做十个人的工作", "angle": "一人公司"},
            {"title": "AI 帮 ADHD 创业者做市场调研", "subtitle": "AI驱动的竞品分析和市场洞察", "angle": "市场调研"},
            {"title": "ADHD 创业者的 AI 产品开发流程", "subtitle": "快速迭代和AI辅助的产品设计", "angle": "产品开发"},
            {"title": "用 AI 帮 ADHD 创业者做内容营销", "subtitle": "AI驱动的内容创作和分发策略", "angle": "内容营销"},
            {"title": "ADHD 的 AI 客服自动化方案", "subtitle": "用AI机器人处理客户咨询", "angle": "客服自动化"},
            {"title": "AI 帮 ADHD 创业者管理财务", "subtitle": "自动记账、现金流预测、税务提醒", "angle": "财务管理"},
            {"title": "ADHD 创业者的 AI 招聘助手", "subtitle": "AI帮你筛选简历和评估候选人", "angle": "招聘"},
            {"title": "用 AI 帮 ADHD 创业者写商业计划书", "subtitle": "AI辅助的商业计划和融资文档", "angle": "商业计划"},
            {"title": "ADHD 的 AI 社交媒体营销自动化", "subtitle": "AI管理多平台社交媒体内容", "angle": "社交营销"},
            {"title": "AI 帮 ADHD 创业者做用户访谈分析", "subtitle": "AI提取用户反馈中的关键洞察", "angle": "用户研究"},
            {"title": "ADHD 创业者的 AI 邮件营销系统", "subtitle": "AI驱动的邮件自动化和个性化", "angle": "邮件营销"},
            {"title": "用 AI 帮 ADHD 创业者做品牌定位", "subtitle": "AI辅助的品牌策略和视觉设计", "angle": "品牌建设"},
            {"title": "ADHD 的 AI SaaS 创业指南", "subtitle": "用AI工具低成本启动SaaS产品", "angle": "SaaS创业"},
            {"title": "AI 帮 ADHD 创业者做数据分析", "subtitle": "AI驱动的业务数据洞察和决策支持", "angle": "数据分析"},
            {"title": "ADHD 创业者的 AI 法律合规助手", "subtitle": "AI帮你处理创业中的法律问题", "angle": "法律合规"},
            {"title": "用 AI 帮 ADHD 创业者建立流程系统", "subtitle": "AI自动化的标准操作流程", "angle": "流程建设"},
            {"title": "ADHD 的 AI 联盟营销策略", "subtitle": "用AI优化联盟营销的收益", "angle": "联盟营销"},
            {"title": "AI 帮 ADHD 创业者管理供应链", "subtitle": "AI驱动的供应商管理和库存优化", "angle": "供应链"},
            {"title": "ADHD 创业者的 AI 定价策略", "subtitle": "AI辅助的竞品定价分析和价格优化", "angle": "定价策略"},
            {"title": "用 AI 帮 ADHD 创业者做 A/B 测试", "subtitle": "AI驱动的快速实验和优化迭代", "angle": "实验优化"},
            {"title": "ADHD 的 AI 电商创业全攻略", "subtitle": "从选品到发货的AI电商方案", "angle": "电商创业"},
            {"title": "AI 帮 ADHD 创业者建立知识付费产品", "subtitle": "AI辅助的课程设计和内容制作", "angle": "知识付费"},
            {"title": "ADHD 创业者的 AI 投资人关系管理", "subtitle": "AI帮你管理投资人沟通和报告", "angle": "投资关系"},
            {"title": "用 AI 帮 ADHD 创业者做竞品监控", "subtitle": "AI自动追踪竞争对手动态", "angle": "竞品分析"},
            {"title": "ADHD 的 AI 社群运营方案", "subtitle": "AI辅助的社群管理和用户增长", "angle": "社群运营"},
            {"title": "AI 帮 ADHD 创业者做产品文档", "subtitle": "AI生成的产品说明和用户手册", "angle": "产品文档"},
            {"title": "ADHD 创业者的 AI 自动化销售漏斗", "subtitle": "从获客到成交的AI自动化流程", "angle": "销售漏斗"},
            {"title": "用 AI 帮 ADHD 创业者做国际化", "subtitle": "AI驱动的多语言和跨文化市场拓展", "angle": "国际化"},
            {"title": "ADHD 的 AI 创意激发系统", "subtitle": "AI帮你把ADHD的创意变成商业机会", "angle": "创意激发"},
            {"title": "AI 帮 ADHD 创业者管理远程团队", "subtitle": "AI辅助的远程团队协调和文化建设", "angle": "远程团队"},
            {"title": "ADHD 创业者的 AI 危机管理方案", "subtitle": "AI驱动的风险预警和危机应对", "angle": "危机管理"},
            {"title": "用 AI 帮 ADHD 创业者做SEO", "subtitle": "AI驱动的搜索引擎优化策略", "angle": "SEO优化"},
            {"title": "ADHD 的 AI 联合创始人匹配", "subtitle": "AI帮你找到互补的创业伙伴", "angle": "合伙人"},
            {"title": "AI 帮 ADHD 创业者做用户增长", "subtitle": "AI驱动的增长黑客策略", "angle": "用户增长"},
            {"title": "ADHD 创业者的 AI 品牌故事讲述", "subtitle": "AI帮你讲好创业故事", "angle": "品牌叙事"},
            {"title": "用 AI 帮 ADHD 创业者管理创业压力", "subtitle": "创业者心理健康的AI辅助方案", "angle": "压力管理"},
            {"title": "ADHD 的 AI 被动收入建设指南", "subtitle": "AI帮你建立自动化的收入来源", "angle": "被动收入"},
            {"title": "AI 帮 ADHD 创业者从0到1的完整路线图", "subtitle": "用AI加速的创业全流程指南", "angle": "创业路线"},
        ],
    ),
    Category(
        id="parenting",
        name="亲子教育",
        name_en="Parenting & Education",
        description="ADHD孩子的AI辅助教育和家庭支持",
        icon="👨‍👩‍👧‍👦",
        color="#14B8A6",
        keywords=["亲子教育", "ADHD儿童", "学校", "家庭", "育儿"],
        angles=["教育策略", "家庭支持", "学校适应", "社交技能", "情感支持"],
        topics=[
            {"title": "AI 如何帮助 ADHD 孩子在学校取得成功", "subtitle": "家长和教师的AI辅助教育方案", "angle": "学校教育"},
            {"title": "ADHD 孩子的 AI 学习伙伴：家长指南", "subtitle": "如何安全有效地为孩子引入AI学习工具", "angle": "家长指南"},
            {"title": "用 AI 帮 ADHD 孩子做作业", "subtitle": "AI辅助作业的正确方式：支持而非替代", "angle": "作业辅导"},
            {"title": "ADHD 孩子的 AI 社交技能训练", "subtitle": "AI模拟社交场景帮助孩子练习", "angle": "社交训练"},
            {"title": "AI 帮 ADHD 家长理解孩子的世界", "subtitle": "用AI学习ADHD教育的最新研究", "angle": "家长教育"},
            {"title": "ADHD 孩子的 AI 阅读兴趣培养", "subtitle": "AI推荐和互动阅读激发阅读动力", "angle": "阅读培养"},
            {"title": "用 AI 帮 ADHD 孩子建立日常作息", "subtitle": "游戏化的AI日程管理", "angle": "作息管理"},
            {"title": "ADHD 青少年的 AI 情绪管理", "subtitle": "AI辅助的青春期情绪调节", "angle": "青少年情绪"},
            {"title": "AI 帮 ADHD 孩子准备考试", "subtitle": "减少考试焦虑的AI学习方案", "angle": "考试准备"},
            {"title": "ADHD 孩子的 AI 兴趣发掘", "subtitle": "AI帮助发现和培养孩子的天赋", "angle": "兴趣发掘"},
            {"title": "用 AI 帮 ADHD 家庭改善亲子沟通", "subtitle": "AI辅助的沟通策略和冲突解决", "angle": "亲子沟通"},
            {"title": "ADHD 孩子的 AI 运动计划", "subtitle": "AI设计的适合ADHD的运动方案", "angle": "运动健康"},
            {"title": "AI 帮 ADHD 孩子建立友谊", "subtitle": "AI辅助的社交技能和友谊维护", "angle": "友谊建设"},
            {"title": "ADHD 孩子的 AI 创意写作课", "subtitle": "利用ADHD的想象力进行AI辅助写作", "angle": "创意写作"},
            {"title": "用 AI 帮 ADHD 孩子管理屏幕时间", "subtitle": "智能屏幕时间控制和引导", "angle": "屏幕管理"},
            {"title": "ADHD 家庭的 AI 假期规划", "subtitle": "减少假期混乱的AI家庭活动规划", "angle": "假期规划"},
            {"title": "AI 帮 ADHD 孩子学习音乐", "subtitle": "AI音乐教学适配ADHD的学习特点", "angle": "音乐教育"},
            {"title": "ADHD 孩子的 AI 安全教育", "subtitle": "AI辅助的安全意识和规则教育", "angle": "安全教育"},
            {"title": "用 AI 帮 ADHD 家长做教育决策", "subtitle": "AI辅助的学校选择和教育路径规划", "angle": "教育决策"},
            {"title": "ADHD 孩子的 AI 编程启蒙", "subtitle": "用AI让ADHD孩子爱上编程", "angle": "编程启蒙"},
            {"title": "AI 帮 ADHD 家长管理自己的情绪", "subtitle": "ADHD家长的自我关怀AI方案", "angle": "家长情绪"},
            {"title": "ADHD 孩子的 AI 时间感知训练", "subtitle": "用AI帮孩子建立时间概念", "angle": "时间训练"},
            {"title": "用 AI 帮 ADHD 孩子做科学实验", "subtitle": "AI辅助的家庭STEM教育", "angle": "科学教育"},
            {"title": "ADHD 孩子的 AI 自信心建设", "subtitle": "AI记录成就、提供正向反馈", "angle": "自信建设"},
            {"title": "AI 帮 ADHD 家庭组织家务分工", "subtitle": "AI驱动的公平家务分配系统", "angle": "家务管理"},
            {"title": "ADHD 孩子的 AI 数学游戏", "subtitle": "游戏化AI数学学习减少数学恐惧", "angle": "数学教育"},
            {"title": "用 AI 帮 ADHD 孩子准备升学", "subtitle": "AI辅助的升学规划和准备", "angle": "升学准备"},
            {"title": "ADHD 兄弟姐妹的 AI 家庭和谐方案", "subtitle": "AI帮助管理ADHD家庭的兄弟姐妹关系", "angle": "兄弟关系"},
            {"title": "AI 帮 ADHD 孩子学习自我管理", "subtitle": "AI辅助的渐进式自主能力培养", "angle": "自我管理"},
            {"title": "ADHD 孩子的 AI 睡眠改善方案", "subtitle": "AI帮助建立健康的睡眠习惯", "angle": "睡眠改善"},
            {"title": "用 AI 帮 ADHD 孩子做艺术创作", "subtitle": "AI艺术工具释放孩子的创造力", "angle": "艺术教育"},
            {"title": "ADHD 家长如何用 AI 与学校老师协作", "subtitle": "AI辅助的家校沟通和协作", "angle": "家校协作"},
            {"title": "AI 帮 ADHD 孩子建立健康饮食习惯", "subtitle": "AI驱动的营养管理和饮食改善", "angle": "饮食健康"},
            {"title": "ADHD 孩子的 AI 旅行学习方案", "subtitle": "旅行中的AI教育和体验学习", "angle": "旅行教育"},
            {"title": "用 AI 帮 ADHD 孩子做情绪日记", "subtitle": "AI引导的儿童情绪表达和记录", "angle": "情绪记录"},
            {"title": "ADHD 家庭的 AI 财商教育", "subtitle": "AI辅助的儿童金钱观和理财教育", "angle": "财商教育"},
            {"title": "AI 帮 ADHD 孩子准备独立生活", "subtitle": "AI辅助的生活技能培养计划", "angle": "独立准备"},
            {"title": "ADHD 孩子的 AI 自然探索活动", "subtitle": "AI引导的户外学习和自然教育", "angle": "自然教育"},
            {"title": "用 AI 帮 ADHD 家庭做教育记录", "subtitle": "AI帮你记录孩子的成长和教育历程", "angle": "成长记录"},
            {"title": "ADHD 家庭的 AI 支持社区", "subtitle": "AI连接的ADHD家庭互助网络", "angle": "社区支持"},
        ],
    ),
    Category(
        id="science",
        name="科学研究",
        name_en="Scientific Research",
        description="ADHD与AI的前沿科学研究和医学进展",
        icon="🔬",
        color="#EF4444",
        keywords=["脑科学", "研究", "诊断", "治疗", "神经科学"],
        angles=["最新研究", "诊断技术", "治疗进展", "脑科学", "药物研究"],
        topics=[
            {"title": "AI 如何革新 ADHD 的诊断方式", "subtitle": "从问卷到AI脑电分析的诊断进化", "angle": "诊断技术"},
            {"title": "ADHD 大脑与 AI 的共鸣：神经科学视角", "subtitle": "ADHD大脑和AI神经网络的相似之处", "angle": "脑科学"},
            {"title": "AI 在 ADHD 药物研发中的突破", "subtitle": "AI加速的ADHD新药发现和优化", "angle": "药物研发"},
            {"title": "用 AI 分析 ADHD 的遗传因素", "subtitle": "基因组学+AI揭示ADHD的遗传密码", "angle": "遗传学"},
            {"title": "AI 脑成像技术揭示 ADHD 大脑的秘密", "subtitle": "最新的AI增强脑扫描研究成果", "angle": "脑成像"},
            {"title": "ADHD 的 AI 预测模型：谁会得 ADHD", "subtitle": "AI早期预测和风险评估", "angle": "风险预测"},
            {"title": "AI 辅助的 ADHD 行为治疗新方法", "subtitle": "数字化认知行为治疗的最新进展", "angle": "行为治疗"},
            {"title": "ADHD 与 AI：注意力的科学本质", "subtitle": "从神经科学角度理解注意力机制", "angle": "注意力科学"},
            {"title": "AI 如何帮助理解 ADHD 的多巴胺系统", "subtitle": "AI模拟的多巴胺通路研究", "angle": "多巴胺"},
            {"title": "ADHD 的 AI 生物标志物发现", "subtitle": "AI在ADHD客观诊断标志物中的突破", "angle": "生物标志"},
            {"title": "用 AI 研究 ADHD 与创造力的关系", "subtitle": "AI数据分析证实ADHD的创造力优势", "angle": "创造力研究"},
            {"title": "AI 在 ADHD 认知训练中的效果研究", "subtitle": "AI认知训练的循证医学证据", "angle": "认知训练"},
            {"title": "ADHD 的 AI 睡眠研究新发现", "subtitle": "AI分析ADHD睡眠模式的最新研究", "angle": "睡眠研究"},
            {"title": "AI 帮助理解 ADHD 的执行功能障碍", "subtitle": "AI模拟和分析执行功能的机制", "angle": "执行功能"},
            {"title": "ADHD 与肠道菌群：AI 揭示的新联系", "subtitle": "AI在微生物组-脑轴研究中的发现", "angle": "肠脑轴"},
            {"title": "AI 如何改善 ADHD 的个性化用药方案", "subtitle": "AI驱动的精准医疗和药物调整", "angle": "精准医疗"},
            {"title": "ADHD 的 AI 神经反馈训练研究", "subtitle": "AI增强的神经反馈治疗效果", "angle": "神经反馈"},
            {"title": "用 AI 研究 ADHD 的性别差异", "subtitle": "AI发现的男女ADHD表现差异", "angle": "性别差异"},
            {"title": "AI 在 ADHD 共病研究中的应用", "subtitle": "AI识别ADHD与焦虑、抑郁的关联模式", "angle": "共病研究"},
            {"title": "ADHD 的 AI 运动处方研究", "subtitle": "AI优化的运动干预方案", "angle": "运动研究"},
            {"title": "AI 如何帮助研究成人 ADHD", "subtitle": "AI在成人ADHD识别和研究中的作用", "angle": "成人ADHD"},
            {"title": "ADHD 的 AI 营养研究", "subtitle": "AI分析饮食对ADHD症状的影响", "angle": "营养研究"},
            {"title": "用 AI 研究 ADHD 的进化优势理论", "subtitle": "ADHD特质在人类进化中的AI分析", "angle": "进化理论"},
            {"title": "AI 辅助的 ADHD 虚拟现实治疗", "subtitle": "VR+AI的沉浸式ADHD治疗方案", "angle": "VR治疗"},
            {"title": "ADHD 的 AI 情绪调节机制研究", "subtitle": "AI揭示ADHD情绪失调的神经机制", "angle": "情绪机制"},
            {"title": "AI 在 ADHD 教育干预研究中的应用", "subtitle": "AI评估教育干预效果的新方法", "angle": "教育研究"},
            {"title": "ADHD 的 AI 数字表型研究", "subtitle": "用手机数据AI分析ADHD行为模式", "angle": "数字表型"},
            {"title": "用 AI 研究 ADHD 的跨文化差异", "subtitle": "全球ADHD数据的AI比较分析", "angle": "跨文化"},
            {"title": "AI 在 ADHD 认知评估中的精准度", "subtitle": "AI认知测试 vs 传统评估工具对比", "angle": "评估工具"},
            {"title": "ADHD 的 AI 可穿戴设备研究", "subtitle": "智能手表和传感器在ADHD监测中的应用", "angle": "可穿戴"},
            {"title": "AI 如何帮助 ADHD 的元认知研究", "subtitle": "AI分析ADHD的自我监控能力", "angle": "元认知"},
            {"title": "ADHD 的 AI 大数据流行病学研究", "subtitle": "AI分析百万级ADHD数据的新发现", "angle": "流行病学"},
            {"title": "用 AI 研究 ADHD 药物的长期效果", "subtitle": "AI分析ADHD药物的长期安全性和有效性", "angle": "长期用药"},
            {"title": "AI 辅助的 ADHD 正念冥想研究", "subtitle": "AI评估正念对ADHD症状的改善效果", "angle": "正念研究"},
            {"title": "ADHD 的 AI 社交认知研究", "subtitle": "AI分析ADHD社交困难的认知机制", "angle": "社交认知"},
            {"title": "AI 在 ADHD 早期干预中的作用", "subtitle": "AI驱动的早期识别和干预策略", "angle": "早期干预"},
            {"title": "ADHD 的 AI 工作记忆训练研究", "subtitle": "AI优化的工作记忆训练方案效果", "angle": "工作记忆"},
            {"title": "用 AI 研究 ADHD 与睡眠呼吸障碍", "subtitle": "AI发现的ADHD-睡眠呼吸关联", "angle": "睡眠呼吸"},
            {"title": "AI 如何推动 ADHD 的去污名化研究", "subtitle": "AI数据驱动的ADHD认知改变", "angle": "去污名化"},
            {"title": "2025 年 ADHD 与 AI 研究的十大突破", "subtitle": "年度最具影响力的ADHD-AI研究盘点", "angle": "年度盘点"},
        ],
    ),
    Category(
        id="lifestyle",
        name="生活方式",
        name_en="Lifestyle",
        description="AI重塑ADHD的日常生活和生活品质",
        icon="🌟",
        color="#A855F7",
        keywords=["生活方式", "健康", "人际关系", "自我成长", "幸福感"],
        angles=["日常生活", "人际关系", "健康管理", "自我成长", "生活品质"],
        topics=[
            {"title": "ADHD 的 AI 生活管家：让每一天都井然有序", "subtitle": "AI全方位的日常生活管理方案", "angle": "日常管理"},
            {"title": "AI 帮 ADHD 建立可持续的晨间仪式", "subtitle": "AI设计的个性化早起流程", "angle": "晨间仪式"},
            {"title": "ADHD 的 AI 饮食管理：吃得更好，想得更清", "subtitle": "AI营养方案优化ADHD的大脑功能", "angle": "饮食管理"},
            {"title": "用 AI 帮 ADHD 建立运动习惯", "subtitle": "AI教练设计的ADHD友好运动计划", "angle": "运动习惯"},
            {"title": "ADHD 的 AI 睡眠优化方案", "subtitle": "从入睡困难到睡眠质量的AI全面改善", "angle": "睡眠优化"},
            {"title": "AI 帮 ADHD 管理人际关系", "subtitle": "AI辅助的社交策略和关系维护", "angle": "人际关系"},
            {"title": "ADHD 的 AI 约会指南", "subtitle": "AI帮你在约会中展现最好的自己", "angle": "恋爱约会"},
            {"title": "用 AI 帮 ADHD 做家庭财务规划", "subtitle": "AI驱动的家庭预算和储蓄计划", "angle": "家庭财务"},
            {"title": "ADHD 的 AI 极简生活方案", "subtitle": "AI帮你减少生活中的决策负担", "angle": "极简生活"},
            {"title": "AI 帮 ADHD 管理慢性病和健康数据", "subtitle": "AI整合的健康数据追踪和管理", "angle": "健康管理"},
            {"title": "ADHD 的 AI 烹饪助手：从买菜到做饭", "subtitle": "AI菜谱推荐和烹饪指导", "angle": "烹饪美食"},
            {"title": "用 AI 帮 ADHD 建立晚间放松仪式", "subtitle": "AI设计的睡前减压流程", "angle": "晚间仪式"},
            {"title": "ADHD 的 AI 个人成长计划", "subtitle": "AI规划的全面自我提升路线图", "angle": "个人成长"},
            {"title": "AI 帮 ADHD 管理搬家和生活变迁", "subtitle": "AI辅助的重大生活变化管理", "angle": "生活变迁"},
            {"title": "ADHD 的 AI 旅行规划全攻略", "subtitle": "从订票到旅途的AI全程管理", "angle": "旅行规划"},
            {"title": "用 AI 帮 ADHD 维护长期友谊", "subtitle": "AI提醒的社交互动和关系维护", "angle": "友谊维护"},
            {"title": "ADHD 的 AI 宠物管理助手", "subtitle": "AI帮你记住喂食、遛狗、看兽医", "angle": "宠物管理"},
            {"title": "AI 帮 ADHD 建立个人护理routine", "subtitle": "AI设计的自我护理和美容流程", "angle": "个人护理"},
            {"title": "ADHD 的 AI 购物决策助手", "subtitle": "AI帮你做出明智的购买决策", "angle": "购物决策"},
            {"title": "用 AI 帮 ADHD 管理数字生活", "subtitle": "密码、订阅、账号的AI统一管理", "angle": "数字生活"},
            {"title": "ADHD 的 AI 社区参与方案", "subtitle": "AI帮你在社区中建立有意义的连接", "angle": "社区参与"},
            {"title": "AI 帮 ADHD 管理家庭维修和保养", "subtitle": "AI提醒的房屋维护和家电保养", "angle": "家庭维修"},
            {"title": "ADHD 的 AI 阅读复兴计划", "subtitle": "AI帮你重新爱上阅读的方案", "angle": "阅读习惯"},
            {"title": "用 AI 帮 ADHD 做志愿服务", "subtitle": "AI匹配的适合ADHD的志愿机会", "angle": "志愿服务"},
            {"title": "ADHD 的 AI 环保生活方案", "subtitle": "AI帮你过上可持续的绿色生活", "angle": "环保生活"},
            {"title": "AI 帮 ADHD 管理生日和纪念日", "subtitle": "再也不忘重要日子的AI提醒系统", "angle": "纪念日管理"},
            {"title": "ADHD 的 AI 早起策略", "subtitle": "AI设计的适合ADHD的唤醒方案", "angle": "早起习惯"},
            {"title": "用 AI 帮 ADHD 建立读书俱乐部", "subtitle": "AI推荐的阅读计划和讨论引导", "angle": "读书社群"},
            {"title": "ADHD 的 AI 节日准备方案", "subtitle": "AI帮你提前准备节日不再手忙脚乱", "angle": "节日准备"},
            {"title": "AI 帮 ADHD 做人生重大决策", "subtitle": "买房、搬家、结婚的AI决策辅助", "angle": "重大决策"},
            {"title": "ADHD 的 AI 兴趣爱好管理", "subtitle": "AI帮你深化爱好而非三分钟热度", "angle": "爱好管理"},
            {"title": "用 AI 帮 ADHD 建立感恩实践", "subtitle": "AI引导的日常感恩和幸福感提升", "angle": "感恩实践"},
            {"title": "ADHD 的 AI 婚姻和伴侣关系指南", "subtitle": "AI辅助的ADHD伴侣关系经营", "angle": "婚姻关系"},
            {"title": "AI 帮 ADHD 管理独居生活", "subtitle": "AI陪伴的独居者生活管理方案", "angle": "独居生活"},
            {"title": "ADHD 的 AI 退休规划", "subtitle": "用AI早期规划ADHD的退休生活", "angle": "退休规划"},
            {"title": "用 AI 帮 ADHD 做家庭活动策划", "subtitle": "AI推荐的适合ADHD家庭的活动", "angle": "家庭活动"},
            {"title": "ADHD 的 AI 冬季自我关怀方案", "subtitle": "AI帮你度过低能量的冬季", "angle": "季节关怀"},
            {"title": "AI 帮 ADHD 建立可持续的自律系统", "subtitle": "AI驱动的渐进式习惯建设", "angle": "自律建设"},
            {"title": "ADHD 的 AI 生活仪式感打造", "subtitle": "AI帮你创建有意义的日常仪式", "angle": "仪式感"},
            {"title": "用 AI 帮 ADHD 活出最好的自己", "subtitle": "AI辅助的ADHD自我实现指南", "angle": "自我实现"},
        ],
    ),
    Category(
        id="community",
        name="社群与文化",
        name_en="Community & Culture",
        description="ADHD社区文化、社会认知和AI驱动的社群建设",
        icon="🌍",
        color="#84CC16",
        keywords=["社群", "文化", "去污名化", "代言", "多元共融"],
        angles=["社群建设", "文化讨论", "去污名化", "名人故事", "未来展望"],
        topics=[
            {"title": "AI 时代的 ADHD 超级英雄：改变世界的 ADHD 名人", "subtitle": "那些有ADHD的科技创新者和企业家", "angle": "名人故事"},
            {"title": "ADHD 社群如何用 AI 建立互助网络", "subtitle": "AI匹配和管理的ADHD支持社群", "angle": "社群建设"},
            {"title": "AI 帮助 ADHD 去污名化：数据说话", "subtitle": "AI数据分析改变社会对ADHD的偏见", "angle": "去污名化"},
            {"title": "ADHD 与 AI 的未来：5 年后的世界", "subtitle": "AI如何从根本上改变ADHD的生活", "angle": "未来展望"},
            {"title": "为什么硅谷如此多 ADHD 创始人", "subtitle": "ADHD特质与科技创业文化的完美匹配", "angle": "科技文化"},
            {"title": "ADHD 的 AI 倡导工具包", "subtitle": "用AI帮助ADHD群体进行权益倡导", "angle": "权益倡导"},
            {"title": "AI 如何帮助 ADHD 家庭讲述自己的故事", "subtitle": "AI辅助的ADHD叙事和故事分享", "angle": "故事分享"},
            {"title": "ADHD 在不同文化中的认知差异", "subtitle": "AI跨文化分析ADHD的社会认知", "angle": "文化差异"},
            {"title": "AI 帮助 ADHD 成年人在职场出柜", "subtitle": "何时、如何在工作中披露ADHD", "angle": "职场披露"},
            {"title": "ADHD 的 AI 在线社群运营指南", "subtitle": "建立活跃ADHD社群的AI策略", "angle": "社群运营"},
            {"title": "AI 如何帮助 ADHD 患者获得更好的医疗资源", "subtitle": "AI匹配的医疗资源和专家推荐", "angle": "医疗资源"},
            {"title": "ADHD 的 AI 自我诊断工具：机遇与风险", "subtitle": "AI自我评估工具的利弊分析", "angle": "自我评估"},
            {"title": "AI 帮助创建 ADHD 友好的工作场所", "subtitle": "AI辅助的无障碍办公环境设计", "angle": "职场友好"},
            {"title": "ADHD 与 AI 伦理：技术如何尊重神经多样性", "subtitle": "AI开发中的ADHD包容性设计原则", "angle": "AI伦理"},
            {"title": "ADHD 的 AI 播客社群", "subtitle": "最值得关注的ADHD+AI播客和社群", "angle": "播客推荐"},
            {"title": "用 AI 做 ADHD 的公益教育", "subtitle": "AI驱动的ADHD科普和教育推广", "angle": "公益教育"},
            {"title": "ADHD 的 AI 辅助社交媒体运营", "subtitle": "ADHD博主如何用AI管理社交媒体", "angle": "社媒运营"},
            {"title": "AI 如何帮助 ADHD 研究者做科研传播", "subtitle": "用AI将ADHD研究转化为大众语言", "angle": "科研传播"},
            {"title": "ADHD 的 AI 互助配对系统", "subtitle": "AI匹配的ADHD伙伴互助计划", "angle": "互助配对"},
            {"title": "AI 帮助 ADHD 家长建立支持小组", "subtitle": "AI组织的ADHD家长互助社群", "angle": "家长社群"},
            {"title": "ADHD 在影视作品中的 AI 分析", "subtitle": "AI分析影视中ADHD角色的正确与错误", "angle": "影视分析"},
            {"title": "用 AI 帮助 ADHD 写自传和回忆录", "subtitle": "AI辅助的个人ADHD故事书写", "angle": "自传写作"},
            {"title": "ADHD 的 AI 多语言社群", "subtitle": "AI翻译打破ADHD社群的语言障碍", "angle": "多语言"},
            {"title": "AI 帮助 ADHD 患者参与临床试验", "subtitle": "AI匹配适合的临床研究机会", "angle": "临床参与"},
            {"title": "ADHD 的 AI 年度调查报告", "subtitle": "AI分析ADHD社群的年度趋势", "angle": "年度报告"},
            {"title": "用 AI 建立 ADHD 导师匹配平台", "subtitle": "AI配对的ADHD导师和受导者", "angle": "导师平台"},
            {"title": "ADHD 与神经多样性运动的 AI 视角", "subtitle": "AI如何推动神经多样性的社会接纳", "angle": "神经多样"},
            {"title": "AI 帮助 ADHD 做消费者权益保护", "subtitle": "AI帮你识别针对ADHD的伪科学产品", "angle": "消费保护"},
            {"title": "ADHD 的 AI 学术圈社群", "subtitle": "ADHD学者和研究者的AI协作平台", "angle": "学术社群"},
            {"title": "用 AI 帮助 ADHD 写公开信和倡议书", "subtitle": "AI辅助的公共政策倡导", "angle": "政策倡导"},
            {"title": "ADHD 的 AI 艺术家社群", "subtitle": "AI帮助ADHD艺术家连接和展示作品", "angle": "艺术社群"},
            {"title": "AI 如何帮助 ADHD 老年人", "subtitle": "AI在老年ADHD管理中的特殊作用", "angle": "老年关怀"},
            {"title": "ADHD 的 AI 职业社群网络", "subtitle": "按行业分类的ADHD职业互助社群", "angle": "职业社群"},
            {"title": "用 AI 帮助 ADHD 做公民参与", "subtitle": "AI辅助ADHD公民的社会参与和投票", "angle": "公民参与"},
            {"title": "ADHD 的 AI 书评和推荐系统", "subtitle": "AI推荐的最佳ADHD相关书籍", "angle": "书籍推荐"},
            {"title": "AI 帮助 ADHD 做跨代际对话", "subtitle": "不同年龄ADHD群体的AI促进对话", "angle": "代际对话"},
            {"title": "ADHD 的 AI 全球地图", "subtitle": "AI可视化的全球ADHD资源和社群地图", "angle": "全球地图"},
            {"title": "用 AI 做 ADHD 的社会经济影响研究", "subtitle": "AI分析ADHD对社会和经济的影响", "angle": "社会影响"},
            {"title": "ADHD × AI：从被忽视到被赋能的转变", "subtitle": "AI时代ADHD群体的赋能故事", "angle": "赋能故事"},
            {"title": "展望2030：ADHD 与 AI 共同进化的美好未来", "subtitle": "未来十年ADHD生活质量的AI提升愿景", "angle": "长期愿景"},
        ],
    ),
]


def get_all_topics() -> list[dict]:
    """获取所有分类中的全部选题"""
    all_topics = []
    for cat in CATEGORIES:
        for i, topic in enumerate(cat.topics):
            all_topics.append({
                "id": f"{cat.id}-{i+1:03d}",
                "category_id": cat.id,
                "category_name": cat.name,
                "category_name_en": cat.name_en,
                "category_icon": cat.icon,
                "category_color": cat.color,
                "title": topic["title"],
                "subtitle": topic["subtitle"],
                "angle": topic["angle"],
                "keywords": cat.keywords,
            })
    return all_topics


def get_category_by_id(category_id: str) -> Category | None:
    """根据ID获取分类"""
    for cat in CATEGORIES:
        if cat.id == category_id:
            return cat
    return None
